version: '3.8'

services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_migrations:/pb_migrations
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - TZ=UTC

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
