services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_migrations:/pb_migrations
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - TZ=UTC

  sveltekit:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./app:/app
    networks:
      - app-network
    environment:
      - VITE_PB_URL=http://localhost:8080/api/pb
      - NODE_ENV=development

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/log/caddy
    depends_on:
      - sveltekit
      - pocketbase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
